### PR TITLE
Refactor main API for simplicity and clarity

### PR DESCRIPTION
**Pull request by drbenmorgan**
This aims to reduce the size of the PTL API to isolate core functionality from that only used in the examples and/or for testing. That's helpful in consumers such as Geant4, where expansion of usage will require more developers/users to be familiar with PTL's primary interfaces. The main changes are:

- PTL's `Timer` and `Backtrace` interfaces are only used in example/test code, with `Singleton` not used anywhere. Whilst useful, they are not required in PTL's core function of tasking, and consumers of PTL will likely have their own solutions.
- The obsolete `TBBTaskGroup` header is removed
- Move `ConsumeParameters`, `ScopeDestructor`, `GetEnv` to dedicated headers to make use/purpose clear
  - The `EnvSettings` singleton is removed as it should be up to the client whether/how to store any needed env vars.
  - Use of environment variables is also generally reduced and simplified with API calls used instead where possible
- Group related functionality into clear headers
    - All preprocessor macros to `Macros.hh`
    - All core types to `Types.hh`
    - `Threading.hh` reduced to thread/core functions only
    - Backports of C++ > 11 features to dedicated detail header
-  Verbosity of output is reduced to minimum/errors
- `ThreadPool`'s destructor is made non-virtual as it provides no virtual functions and does not appear designed to be inherited from.
  - Its construction is also simplified to _only_ use the related `Config` object. 

A final clang-format has been applied to the changes using clang-format 16, together with a bump of the max supported CMake to 3.26.

### CODE REVIEW

**Comment by jrmadsen** [comment]
Hey @drbenmorgan, this looks good to me but we should probably bump up the major version. 

I’m probably going to pull in https://github.com/jrmadsen/PTL/commit/f0205c1935f14861b05152378b7ac1c9234cddc0 with some minor refinements (i.e. support some config fields) after this is merged as a way to guarantee all the threads in the pool have started before it returns.

**Comment by drbenmorgan** [comment]
Hi @jrmadsen, thanks! Agree on the major version but I'll leave that to you unless you'd prefer the bump to go in here?

**Comment by drbenmorgan** [comment]
Hi @jrmadsen, I _think_ the Ubuntu 18.04 CI jobs aren't running because AFAICT GitHub have [retired the 18.04 runner](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). I guess if support for that is still needed, it would need to use Docker on the more recent platforms, or the older compilers could be run on the newer versions.

I'd suspect if the changes here are passing on newer GCC/Clang it should be o.k. on the older versions...

**Comment by jrmadsen** [comment]
Yeah I think we can drop the Ubuntu 18.04 tests

**Comment by drbenmorgan** [comment]
O.k., Ubuntu 18.04 builds dropped with the additional checks now running on 20.04. I've also put in one more fix removing unused/adding needed headers as suggested by `include-what-you-use`.

I think this is ready to go, though I'd like to put in one more, separate PR on top of this one after it's merged (on environment variable cleanup) before the major version bump.

**Pull request merged**
